In [1]:
import torch

### Prediction <br/>

Creating the following expressions

$b=-1,w=2$

$\hat{y}=-1+2x$

In [2]:
# Define parameters w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

Define the function <code>forward(x, w, b)</code> makes the prediction:

In [3]:
# Function forward(x) for prediction

def forward(x):
    yhat = w * x + b
    return yhat

Making predictions for x=1

$\hat{y}=-1+2x$

$\hat{y}=-1+2(1)$

In [4]:
# Predict y = 2x - 1 at x = 1

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


### Prediction for multiple inputs

construct the <code>x</code> tensor first then check the shape of <code>x</code>.

In [5]:
# Create x Tensor and check the shape of x tensor

x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


Making a prediction of the following <code>x</code> tensor using the <code>w</code> and <code>b</code> from above.


In [7]:
# Make a prediction of y = 2x - 1 at x = [[1.0], [2.0], [3.0]]

x = torch.tensor([[1.0], [2.0], [3.0]])
print("The shape of x: , x.shape")

# Make the prediction
yhat = forward(x)
print("The prediction: ", yhat)

The shape of x: , x.shape
The prediction:  tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


<h3 id="Linear">Class Linear</h3>

1. The linear class can be used to make a prediction and the linear class to build more complex models.
2. Set the random seed because the parameters are randomly initialized
3.  linear object using the constructor and the parameters are already randomly created. I am printing out to see what <i>w</i> and <i>b</i>.
4. The parameters of an <code>torch.nn.Module</code> model are contained in the model’s parameters accessed with <code>lr.parameters()</code>
5. equivalent to this below:

$b=-0.44, w=0.5153$<br/>
$\hat{y}=-0.44+0.5153x$

In [8]:
from torch.nn import Linear

torch.manual_seed(1)
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


 <code>state_dict()</code> Returns a Python dictionary object corresponding to the layers of each parameter  tensor.

In [9]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [10]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


Making a single prediction at <i>x = [[1.0]]</i>.

In [11]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739]], grad_fn=<AddmmBackward0>)


I can also use the model <code>lr(x)</code> to predict multiple results

In [12]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


Making a prediction of the following <code>x</code> tensor using the linear regression model <code>lr</code>.

In [13]:
# Use the linear regression model object lr to make the prediction.

x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)


### Building a Custom Model

In [14]:
from torch import nn

class LR_model(nn.Module):
  # constructor
  def __init__(self, input_size, output_size):
    # inheriting from the parent
    super(LR_model, self).__init__()
    self.linear = nn.Linear(input_size, output_size)

  # prediction function
  def forward(self, x):
    yhat = self.linear(x)
    return yhat

Creating the object using the constructor and printing the paramenters + model.

In [15]:
lr = LR_model(1,1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [16]:
# Try our customize linear regression model with single input

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755]], grad_fn=<AddmmBackward0>)


Storing the parameters in a dictionary.

In [17]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.1939]])), ('linear.bias', tensor([0.4694]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.1939]]), tensor([0.4694])])


Creating an object <code>lr1</code> from the class created before and making a prediction.

In [18]:
# Use the LR class to create a model and make a prediction of the following tensor.

x = torch.tensor([[1.0], [2.0], [3.0]])

lr1 = LR_model(1,1)
yhat = lr1(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.3417],
        [-1.2832],
        [-2.2246]], grad_fn=<AddmmBackward0>)
